# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for pip
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/python/" # Location of the requirements file, relative to the root of the repository.
    schedule:
      interval: "weekly"
    ignore:
      # ignore patch level updates for any dependency
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

    # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # For GitHub Actions, set the directory to / to check for workflow files in .github/workflows.
    schedule:
      interval: "weekly"
    ignore:
      # ignore patch level updates for any dependency
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
