version: '3'

services:
  sppmon:
      image: sppmon
      container_name: sppmon
      build:
          context: ./
          dockerfile: Dockerfile
      volumes:
        # https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3
        # have to check this
        #- type: volume
        #  source: ./config_files/
        #  target: /usr/src/app/config_files
        #  read_only: true
        - ./config_files/:/usr/src/app/config_files:ro,Z
        - /home/sppmon/sppmonLogs:/root/sppmonLogs:Z
      networks:
          - influx-network
  influx:
    image: influxdb:1.8.6
    container_name: influx
    ports:
      - 8086:8086
    volumes:
      - influx-storage:/var/lib/influxdb
      - .influx.conf:/etc/influxdb/influx.conf
    networks:
      - influx-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - influx-network

volumes:
  grafana-storage:
      external: false
  influx-storage:
      external: false

networks:
  influx-network:
    driver: bridge
