{
 "title": "SPPCheck for IBM Spectrum Protect Plus",
 "description": "Dashboard for dynamic display of the SPPCheck Results",
 "tags": [
  "spp_check",
  "v1.0"
 ],
 "time": { "from": "now-1y", "to": "now+1y" },
 "templating": {
  "list": [
   { "name": "server", "query": "influxdb" },
   { "name": "prediction", "query": "SHOW RETENTION POLICIES" },
   { "name": "excel", "query": "SHOW RETENTION POLICIES" },
   { "name": "rp", "label": "Latest Data / Fakedata", "query": "rp_inf, rp_days_90, fakeData" }
  ]
 },
 "panels": [
  { "title": "SPPCheck Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vSnap Storage Prediction",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Historical & Prediction Used Data",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "physical_capacity" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Total" }
     ]
    },
    {
     "alias": "Historical & Prediction Total Size",
     "measurement": "sppcheck_data",
     "query": "SELECT \"data\" FROM \"$prediction\".\"sppcheck_data\" WHERE (\"metric_name\" = 'physical_pool_size' AND \"grouping_tag\" = 'Total Prediction' OR \"grouping_tag\" = 'Total Historic') AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "physical_pool_size" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Total" }
     ]
    },
    { "expression": "$Available - $Used\n", "type": "math" },
    { "expression": "($Used / $Available) * 100", "type": "math" }
   ]
  },
  {
   "title": "vSnap Storage Setup Check",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "primary_vsnap_size_est_subtotal"
      }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation Reserve",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "primary_vsnap_size_est_w_reserve"
      }
     ]
    },
    {
     "alias": "Historical & Prediction Total Size",
     "measurement": "sppcheck_data",
     "query": "SELECT \"data\" FROM \"$prediction\".\"sppcheck_data\" WHERE (\"metric_name\" = 'physical_pool_size' AND \"grouping_tag\" = 'Total Prediction' OR \"grouping_tag\" = 'Total Historic') AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "physical_pool_size" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Total" }
     ]
    },
    {
     "downsampler": "mean",
     "expression": "Excel",
     "reducer": "last",
     "settings": { "mode": "" },
     "type": "reduce",
     "upsampler": "pad",
     "window": "7d"
    },
    {
     "downsampler": "mean",
     "expression": "Reserve",
     "reducer": "last",
     "settings": { "mode": "" },
     "type": "reduce",
     "upsampler": "pad",
     "window": "7d"
    },
    { "expression": "$Available - $Reduce_Excel", "type": "math" },
    { "expression": "$Available - $Reduce_Reserve", "type": "math" }
   ]
  },
  {
   "title": "Server Memory Prediction",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Used",
     "measurement": "sppcheck_data",
     "query": "SELECT \"data\" FROM \"$prediction\".\"sppcheck_data\" WHERE (\"metric_name\" = 'total_server_memory') AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_memory" }
     ]
    },
    {
     "alias": "Available",
     "measurement": "sppcheck_data",
     "query": "SELECT \"data\" FROM \"$prediction\".\"sppcheck_data\" WHERE (\"metric_name\" = 'total_server_memory') AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_memory" }
     ]
    },
    { "expression": "$Available - $Used", "type": "math" },
    { "expression": "($Used / $Available) * 100", "type": "math" }
   ]
  },
  {
   "title": "Server Memory Check",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Available",
     "measurement": "sppcheck_data",
     "query": "SELECT \"data\" FROM \"$prediction\".\"sppcheck_data\" WHERE (\"metric_name\" = 'total_server_memory') AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_memory" }
     ]
    },
    {
     "alias": "Excel Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_memory" }
     ]
    },
    { "expression": "$Available - $Excel_Resampled", "type": "math" },
    { "expression": "Excel", "reducer": "last", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "vSnap Total Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Existing",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "vsnap_count" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Total" }
     ]
    },
    {
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "primary_vsnap_count" }
     ]
    },
    { "expression": "Excel", "reducer": "last", "type": "reduce" },
    { "expression": "$Existing- $Reduce_Excel", "type": "math" }
   ]
  },
  {
   "title": "Server Configuration Catalog Prediction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Configuration" }
     ]
    },
    {
     "alias": "Prediction",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Configuration" }
     ]
    },
    { "expression": "$Available - $Used", "type": "math" }
   ]
  },
  {
   "title": "Server Configuration Catalog Prediction",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Configuration" }
     ]
    },
    {
     "alias": "Prediction",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Configuration" }
     ]
    },
    { "expression": "($Used / $Available) * 100", "type": "math" }
   ]
  },
  {
   "title": "Catalog Configuration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Configuration" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_config_catalog" }
     ]
    },
    { "expression": "$Available - $Reduce_Excel", "type": "math" },
    { "expression": "Excel", "reducer": "last", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Server Recovery Catalog Prediction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Recovery" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "grouping_tag", "operator": "=", "value": "Recovery" },
      { "condition": "AND", "key": "metric_name", "operator": "=", "value": "total_server_catalogs" }
     ]
    },
    { "expression": "$Available - $Used", "type": "math" }
   ]
  },
  {
   "title": "Server Recovery Catalog Prediction",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Recovery" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "grouping_tag", "operator": "=", "value": "Recovery" },
      { "condition": "AND", "key": "metric_name", "operator": "=", "value": "total_server_catalogs" }
     ]
    },
    { "expression": "($Used /$Available) * 100", "type": "math" }
   ]
  },
  {
   "title": "Recovery Catalog",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "grouping_tag", "operator": "=", "value": "Recovery" },
      { "condition": "AND", "key": "metric_name", "operator": "=", "value": "total_server_catalogs" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_recovery_catalog" }
     ]
    },
    { "expression": "Excel", "reducer": "last", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "$Available - $Reduce_Excel", "type": "math" }
   ]
  },
  {
   "title": "VADP Total Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Existing",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "vadp_count_total" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Total" }
     ]
    },
    {
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "primary_vadp_count_total" }
     ]
    },
    { "expression": "Excel", "reducer": "last", "type": "reduce" },
    { "expression": "$Existing - $Reduce_Excel", "type": "math" }
   ]
  },
  {
   "title": "Server System Catalog Prediction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "System" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "grouping_tag", "operator": "=", "value": "System" },
      { "condition": "AND", "key": "metric_name", "operator": "=", "value": "total_server_catalogs" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_config_system" }
     ]
    },
    { "expression": "Excel", "reducer": "last", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "$Available -$Used", "type": "math" },
    { "expression": "$Available - $Reduce_Excel", "type": "math" }
   ]
  },
  {
   "title": "Server System Catalog Prediction",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "System" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "grouping_tag", "operator": "=", "value": "System" },
      { "condition": "AND", "key": "metric_name", "operator": "=", "value": "total_server_catalogs" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_config_system" }
     ]
    },
    { "expression": "Excel", "reducer": "last", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "$Available - $Reduce_Excel", "type": "math" },
    { "expression": "($Used / $Available) * 100", "type": "math" }
   ]
  },
  {
   "title": "Server File Catalog Prediction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "File" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "grouping_tag", "operator": "=", "value": "File" },
      { "condition": "AND", "key": "metric_name", "operator": "=", "value": "total_server_catalogs" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_config_file" }
     ]
    },
    { "expression": "Excel", "reducer": "last", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "$Available -$Used", "type": "math" },
    { "expression": "$Available - $Reduce_Excel", "type": "math" }
   ]
  },
  {
   "title": "Server File Catalog Prediction",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "File" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "grouping_tag", "operator": "=", "value": "File" },
      { "condition": "AND", "key": "metric_name", "operator": "=", "value": "total_server_catalogs" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_config_file" }
     ]
    },
    { "expression": "Excel", "reducer": "last", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "$Available - $Reduce_Excel", "type": "math" },
    { "expression": "($Used / $Available) * 100", "type": "math" }
   ]
  },
  { "title": "Storage Prediction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "vSnap used storage Prediction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Prediction $tag_grouping_tag_name",
     "groupBy": [
      { "params": [ "grouping_tag" ], "type": "tag" },
      { "params": [ "grouping_tag_name" ], "type": "tag" }
     ],
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "physical_capacity" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "primary_vsnap_size_est_subtotal"
      }
     ]
    },
    {
     "alias": "Historic $tag_hostAddress",
     "groupBy": [
      { "params": [ "storageId" ], "type": "tag" },
      { "params": [ "hostAddress" ], "type": "tag" }
     ],
     "measurement": "storages",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation Reserve",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "primary_vsnap_size_est_w_reserve"
      }
     ]
    }
   ]
  },
  {
   "title": "vSnap Total storage Prediction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Prediction $tag_grouping_tag_name $tag_grouping_tag",
     "groupBy": [
      { "params": [ "grouping_tag" ], "type": "tag" },
      { "params": [ "grouping_tag_name" ], "type": "tag" }
     ],
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "physical_pool_size" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "primary_vsnap_size_est_subtotal"
      }
     ]
    },
    {
     "alias": "Historic $tag_hostAddress $tag_storageId",
     "groupBy": [
      { "params": [ "storageId" ], "type": "tag" },
      { "params": [ "hostAddress" ], "type": "tag" }
     ],
     "measurement": "storages",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation Reserve",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "primary_vsnap_size_est_w_reserve"
      }
     ]
    }
   ]
  },
  {
   "title": "vSnap Storage Prediction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Historical & Prediction Used Data",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "physical_capacity" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Total" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "primary_vsnap_size_est_subtotal"
      }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation Reserve",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "primary_vsnap_size_est_w_reserve"
      }
     ]
    },
    {
     "alias": "Historical & Prediction Total Size",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "physical_pool_size" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  { "title": "SPP Server Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Used Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_memory" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_memory" }
     ]
    },
    {
     "alias": "Historic",
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "memorySize" ], "type": "field" },
       { "params": [ "* memoryUtil" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_memory" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_memory" }
     ]
    },
    {
     "alias": "Historic Total",
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "memorySize" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Memory used vs total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "query": "SELECT \"data\" FROM \"$prediction\".\"sppcheck_data\" WHERE (\"metric_name\" = 'total_server_memory') AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_memory" }
     ]
    },
    {
     "alias": "Historic Used",
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "memorySize" ], "type": "field" },
       { "params": [ "* memoryUtil" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Historic Total",
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "memorySize" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Prediction Used",
     "measurement": "sppcheck_data",
     "query": "SELECT \"data\" FROM \"$prediction\".\"sppcheck_data\" WHERE (\"metric_name\" = 'total_server_memory') AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_memory" }
     ]
    },
    {
     "alias": "Excel Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_memory" }
     ]
    }
   ]
  },
  { "title": "Server Catalogs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Server Catalog Configuration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Configuration" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_config_catalog" }
     ]
    },
    {
     "alias": "Historic",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "usedSize" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Configuration" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Configuration" }
     ]
    },
    {
     "alias": "Historic Total",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "totalSize" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Configuration" }
     ]
    }
   ]
  },
  {
   "title": "Server Recovery Catalog ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Recovery" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_recovery_catalog" }
     ]
    },
    {
     "alias": "Historic",
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "usedSize" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Recovery" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "Recovery" }
     ]
    },
    {
     "alias": "Historic Total",
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "totalSize" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Recovery" }
     ]
    }
   ]
  },
  {
   "title": "Server File Configuration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "File" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_config_file" }
     ]
    },
    {
     "alias": "Historic",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "usedSize" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "File" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "File" }
     ]
    },
    {
     "alias": "Historic Total",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "totalSize" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "File" }
     ]
    }
   ]
  },
  {
   "title": "Server System Configuration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Prediction",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "used_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "System" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "spp_config_system" }
     ]
    },
    {
     "alias": "Historic",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "usedSize" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "System" }
     ]
    },
    {
     "alias": "Prediction Total",
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "total_server_catalogs" },
      { "condition": "AND", "key": "grouping_tag", "operator": "=", "value": "System" }
     ]
    },
    {
     "alias": "Historic Total",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "totalSize" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  { "title": "vSnap & VADP Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "vSnap Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "History and Prediction",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "vsnap_count" },
      { "condition": "AND", "key": "site", "operator": "=", "value": "Total" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "primary_vsnap_count" }
     ]
    }
   ]
  },
  {
   "title": "VADP Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "History and Prediction",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "sppcheck_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "vadp_count_total" },
      { "condition": "AND", "key": "site", "operator": "=", "value": "Total" }
     ]
    },
    {
     "alias": "Blueprint Sizer Estimation",
     "measurement": "sppcheck_excel_data",
     "select": [
      [
       { "params": [ "data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "primary_vadp_count_total" }
     ]
    }
   ]
  },
  {
   "title": "Hidden",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "DUMMY",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "RP $tag_hostAddress",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "hostAddress" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "storages",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostAddress", "operator": "=~", "value": "/.*15.*/" }
       ]
      }
     ]
    },
    {
     "title": "Excel-All",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_metric_name",
       "groupBy": [
        { "params": [ "metric_name" ], "type": "tag" }
       ],
       "measurement": "sppcheck_excel_data",
       "select": [
        [
         { "params": [ "data" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}