version: '3'

services:
  sppmon:
      image: sppmon
      container_name: sppmon
      build:
          context: ./
          dockerfile: Dockerfile
      networks:
          - influx-network
  influx:
    user: test
    image: influxdb:1.8.6
    ports:
      - 8086:8086
    volumes:
      - ./docker-storage/influxDB:/var/lib/influxdb
      - ./docker-storage/influx.conf:/etc/influxdb/influx.conf
    networks:
      - influx-network

  grafana:
    user: test
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./docker-storage/grafana:/var/lib/grafana
    networks:
      - influx-network

networks:
  influx-network:
    driver: bridge
